### ISSUE TITLE
Cannot track same task with 2 different descriptions

### ISSUE THREAD

**Issue by Nonda95** [szymonkozak/tempomat#9]
Currently, I cannot track the same task with `tracker:start`, because only one tracker per task is allowed, and `tracker:resume` doesn't have a possibility to add a description. 

Could you allow using multiple trackers for a task (with a unique task and description) or adding a different description when resuming a particular tracker?

**Comment by MiSikora** [comment]
Changing descriptions for one tracker might become too complicated to use in my opinion. Trackers can have only one description which is attached to all resume/pause intervals. It is also possible to overwrite descriptions of all tracking intervals with the `stop` command. What you can do right now instead of pausing and resuming is to just stop the original tracker.

```sh
tempo tracker:start ABC-123 -d "First description."
tempo tracker:stop ABC-123
tempo tracker:start ABC-123 -d "Second description."
```

The solution with custom IDs is viable but still cumbersome to use as I see it. You could argue that now you have to remember the first description to restart the tracker, but on the other hand, you would need to remember the unique ID that you assigned to the tracker anyway. What might come in handy is a `--stop-previous` flag for the `tracker:start` command, that could stop the previous tracker and upload it before starting a new one. To make it easier you can create an alias to always use the flag.

```sh 
tts ABC-123 -d "First description"
tts ABC-123 -d "Second description" # Stops the previous tracker and uploads it before starting this one.
```

Would this solve your problems or do you see some issues with this approach?
